# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0b94eb6a712eeac20c25fd483ca58729b5b90c0fb90a62b78e372d2a659858d1efd3698a382121625d00a58cda85c8d2b5a04fde581333a6281b0d86b88b775

test:
  secret_key_base: c3e2d6d6aaaf51a517e98789264eca69b50086334a87cc0d9041d99358765d9f9063eac072a8ddd69f146a2cf9cd06fa9fddcbcf7e0d76ed693b147a2a3fe594

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
